### ISSUE TITLE
automatizacion del acceso

### ISSUE THREAD

**Issue by jsorianogit** [inteli-code/ERP-IECESSA#3]
se requiere que la pantalla de la colmena, se realize automaticamente....

dudas con jose soriano

**Comment by acuellargit** [comment]
➤ August Galmich commented:
checar automatizacion

**Comment by acuellargit** [comment]
Close #3

**Comment by acuellargit** [comment]
➤ August Galmich commented:
Close #3

**Comment by acuellargit** [comment]
close #

**Comment by acuellargit** [comment]
➤ August Galmich commented:
close #3
